import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        crypto: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        Audio: "readonly",
        SpeechSynthesisUtterance: "readonly",
        URL: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        alert: "readonly",
        confirm: "readonly",
        DOMParser: "readonly",
        HTMLElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLOptionElement: "readonly",
        HTMLFormElement: "readonly",
        HTMLSpanElement: "readonly",
        HTMLParagraphElement: "readonly",
        HTMLTemplateElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        FocusEvent: "readonly",
        InputEvent: "readonly",
        TouchEvent: "readonly",
        WheelEvent: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        Node: "readonly",
        Element: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        performance: "readonly",
        AbortController: "readonly",
        TextDecoder: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
      "no-var": "error",
      "prefer-const": "error",
      "eqeqeq": ["error", "smart"],
      "semi": ["error", "never"],
      "quotes": ["error", "double", { avoidEscape: true }],
      "indent": ["error", 2, { SwitchCase: 1 }],
      "no-unused-expressions": "warn",
      "no-redeclare": "error",
      "no-empty": "warn",
      "no-useless-assignment": "warn",
    },
  },
  {
    // dist/ is build output — skip lint
    ignores: ["dist/**", "backend/**", "src-tauri/**", "node_modules/**"],
  },
];
